import {Platform, StyleSheet} from 'react-native';
import {moderateScale, textScale} from '../../../styles/responsiveSize';
import colors from '../../../constants/colors';
import fontFamily from '../../../styles/fontFamily';

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentContainer: {
    backgroundColor: colors.WHITE,
    width: '90%',
    borderRadius: moderateScale(10),
    padding: moderateScale(20),
    height: Platform.OS === 'android' ? moderateScale(530) : moderateScale(490),
  },
  buttonContainer: {
    marginTop: moderateScale(30),
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonTextStyle: {
    fontSize: textScale(18),
    color: colors.WHITE,
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
  },
  buttonStyle: {
    backgroundColor: colors.BLACK,
    width: '75%',
    borderRadius: moderateScale(60),
  },
  selectContainer: {
    marginTop: moderateScale(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleExtended: {
    fontSize: textScale(18),
    fontFamily: fontFamily.POPP,
    color: colors.NAVY_BLUE,
  },
  deliveryContainer: {marginTop: moderateScale(30)},
  titleDelivery: {
    fontSize: textScale(16),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
    textAlign: 'left',
  },
  dateContainer: {
    marginTop: moderateScale(5),
    width: '100%',
    height: moderateScale(50),
    backgroundColor: colors.NAVY_BLUE,
    borderRadius: moderateScale(5),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateInnerContainer: {
    backgroundColor: colors.WHITE,
    width: '40%',
    height: moderateScale(35),
    borderRadius: moderateScale(2),
    marginHorizontal: moderateScale(10),
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  dateTitle: {
    fontSize: textScale(12),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
    textAlign: 'left',
  },
  calendarIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.LIGHT_BLUE,
  },
  timeContainer: {
    backgroundColor: colors.WHITE,
    width: '40%',
    height: moderateScale(35),
    borderRadius: moderateScale(2),
    marginHorizontal: moderateScale(10),
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  timeTitle: {
    fontSize: textScale(12),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
  },
  clockImage: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.LIGHT_BLUE,
  },
  extendedDateContainer: {marginTop: moderateScale(30)},
  extendedDateTitle: {
    fontSize: textScale(16),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
    textAlign: 'left',
  },
  extendedInnerContainer: {
    marginTop: moderateScale(5),
    width: '100%',
    height: moderateScale(50),
    backgroundColor: colors.NAVY_BLUE,
    borderRadius: moderateScale(5),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  totalContainer: {
    marginTop: moderateScale(30),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  totalLabel: {
    fontSize: textScale(14),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
  },
  totalAmount: {
    fontSize: textScale(14),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
  },
  dottedLine: {
    width: '100%',
    height: moderateScale(1),
    top: moderateScale(4),
  },
  currencyTitle: {
    fontSize: textScale(14),
    fontFamily: fontFamily.POPPINS_BOLD,
    color: colors.NAVY_BLUE,
  },
  totalTitle: {
    fontSize: textScale(14),
    fontFamily: fontFamily.POPPINS_BOLD,
    color: colors.NAVY_BLUE,
  },
  totalMainContainer: {
    marginTop: moderateScale(10),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dottedImage: {
    width: '100%',
    height: moderateScale(1),
    top: moderateScale(4),
  },
  titleExtend: {
    fontSize: textScale(14),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
  },
  extendTitleContainer: {
    marginTop: moderateScale(10),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  outStandingTitle: {
    fontSize: textScale(14),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
  },
  outStandingContainer: {
    marginTop: moderateScale(30),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  imageClock: {
    width: moderateScale(20),
    height: moderateScale(20),
    tintColor: colors.LIGHT_BLUE,
  },
  timeTitle: {
    fontSize: textScale(12),
    fontFamily: fontFamily.POPPINS_SEMI_BOLD,
    color: colors.NAVY_BLUE,
  },
  timeMainContainer: {
    backgroundColor: colors.WHITE,
    width: '40%',
    height: moderateScale(35),
    borderRadius: moderateScale(2),
    marginHorizontal: moderateScale(10),
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  extendDateMainContainer: {
    backgroundColor: colors.WHITE,
    width: '40%',
    height: moderateScale(35),
    borderRadius: moderateScale(2),
    marginHorizontal: moderateScale(10),
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  extendDateMainnContainer: {
    marginTop: moderateScale(5),
    width: '100%',
    height: moderateScale(50),
    backgroundColor: colors.NAVY_BLUE,
    borderRadius: moderateScale(5),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  titleExtended: {
    fontSize: textScale(18),
    fontFamily: fontFamily.POPPINS_BOLD,
    color: colors.NAVY_BLUE,
  },
});

export default styles;
