export class CarInquiry {
  constructor(
    bookingId: string,
    name: string,
    carName: string,
    startDate: Date,
    isNewCar: boolean,
    endDate: Date,
    pickUpLoc: string,
    dropLocation: string,
    phoneNumber: string,
    message: string,
    deliveryMode: string, 
    email: string,
    packages: string,
    brand: string,
    model: string,
    status: string,
    pickupTime: Date | string,
    dropTime: Date | string,
    statusMessage: string,
    statusChangedBy: string,
    bookingCreated?: Date | string,
    bookingUpdated?: Date | string,
  ) {
    return {
      bookingId: bookingId,
      carName: carName,
      startDate: startDate,
      endDate: endDate,
      pickUpLoc: pickUpLoc,
      dropLocation: dropLocation,
      isNewCar:isNewCar,
      phoneNumber: phoneNumber,
      message: message,
      deliveryMode: deliveryMode, 
      name: name,
      email: email,
      packages: packages,
      brand: brand,
      model: model,
      status: status,
      pickupTime: pickupTime,
      dropTime: dropTime,
      statusMessage: statusMessage,
      statusChangedBy: statusChangedBy,
      bookingCreated: bookingCreated,
      bookingUpdated: bookingUpdated
    };
  }
}
