export const dataSetter = (data) => {
    let value = {
        _id: "",
        brand: "",
        model: "",
        category: "",
        year: "",
        location: "",
        vehicleType: "",
        status: "",
        interiorColor: [],
        exteriorColor: [""],
        image: [],
        externalImage: [],
        actualPriceDaily: "",
        discountedPriceDaily: "",
        actualPriceWeekly: "",
        discountedPriceWeekly: "",
        actualPriceMonthly: "",
        discountedPriceMonthly: "",
        transmission: "",
        engineCapacity: "",
        laggageBootCapacity: "",
        securityDeposit: "",
        cashType: [],
        paiInsuranceMonthly: "",
        paymentType: [],
        seater: "",
        freeDailyKM: "",
        freeWeeklyKM: "",
        freeMonthlyKM: "",
        cdwDaily: "",
        cdwWeekly: "",
        cdwMonthly: "",
        additionalMileageCharge: "",
        excessClaimCharge: "",
        salikTollCharge: "",
        keyFeatures: [""],
        unlimitedKMDaily: "",
        unlimitedKMWeekly: "",
        unlimitedKMMonthly: "",
        babySeatChargeDaily: "",
        deliveryChargeDaily: "",
        babySeatChargeWeekly: "",
        deliveryChargeWeekly: "",
        babySeatChargeMonthly: "",
        deliveryChargeMonthly: "",
        additionalDriverChargeDaily: "",
        additionalDriverChargeWeekly: "",
        additionalDriverChargeMonthly: "",
        subsPackage: [],
        airportPickupCharge: "",
        airportDeliveryCharge: "",
        carProvider: "",
        branchLocation: "",
        isOfferApplied: "",
        offerType: "",
        oneMonthPriceOf2500Km: "",
        threeMonthPriceOf2500Km: "",
        sixMonthPriceOf2500Km: "",
        nineMonthPriceOf2500Km: "",
        oneMonthPriceOf5000Km: "",
        threeMonthPriceOf5000Km: "",
        sixMonthPriceOf5000Km: "",
        nineMonthPriceOf5000Km: "",
        fuel: "",
        maxPower: "",
        torque: "",
    }
    if (data) {
        let result = Object.assign(value, data)
        return result
    }
    return value
}