export const ASYNC_ROUTES = {
  LOGIN: 'login',
  SIGN_UP: 'signUp',
  GET_ALL_CARS: 'getAllCars',
  GET_ALL_CARS_CATEGORY: 'getAllCarCategory',
  GET_ALL_CARS_LOCATION: 'getAllCarsLocation',
  GET_CARS_BY_ID: 'getCarsById',
  GET_ALL_SETTINGS: 'getAllSettings',
  CREATE_INQUIRY: 'createInquiry',
  GET_INQUIRY: 'getInquiry',
  GET_ALL_ADDRESS: 'getAllAddress',
  GET_ADDRESS_BY_ID: 'getAddressById',
  GET_ALL_BRANCHES: 'getAllBranches',
  GET_ALL_WALLET: 'getAllWallet',
  GET_ALL_BOOKING_HISTORY: 'getAllBookingHistory',
  GET_USER_BY_ID: 'getUserById',
  UPDATE_ACCOUNT: 'updateAccount',
  LOG_OUT: 'logOut',
  CREATE_DOCUMENT: 'createDocument',
  GET_ALL_DOCUMENTS: 'getAllDocuments',
  GET_ADDRESS: 'getAddress',
  DELETE_DOCUMENT_BY_ID: 'deleteDocumentById',
  UPDATE_DOCUMENT_BY_ID: 'updateDocumentById',
};
export const THUNK_STATUS = {
  LOADING: 'loading',
  SUCCESS: 'success',
  FAILED: 'failed',
};
